apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-n1742466723351
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-n1742466723351
  name: chatbot-n1742466723351
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
