apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-n1742466723351
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-n1742466723351
  name: chatbot-n1742466723351
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-n1742466723351
